name: PR
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: stable
      - name: Dependencies
        run: go mod tidy
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=10m
      - name: test
        run: make test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .tests/coverage.html
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}