name: PR
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.x'
      - name: Dependencies
        run: go mod tidy
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=10m
      - name: test
        run: make test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .tests/coverage.html